services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./files_drop_zone:/my_files_drop_zone  # Bind mount for SQL dumps and other files
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./files_drop_zone:/my_files_drop_zone  # Bind mount for session and other files
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local

networks:
  my_network:
    driver: bridge
